### ISSUE TITLE
The links to browse assume that it is a way

### ISSUE THREAD

**Issue by craigloftus** [jones139/BrewMap#1]
The link to http://www.openstreetmap.org/browse/way/812411807, should be, http://www.openstreetmap.org/browse/node/812411807. I appreciate that particular feature is probably just an initial hack.

**Comment by jones139** [comment]
Should be fixed now - added an extra entity to the data for each brewery to say if it came from a node or a way so we link to the right page.

**Comment by craigloftus** [comment]
Fixed.
