### ISSUE TITLE
Render 'industrial=brewery' rather than 'industry=brewery'

### ISSUE THREAD

**Issue by jones139** [jones139/BrewMap#10]
The proposed tagging scheme has changed to be 'industrial=brewery'.  Breweries tagged like this are appearing in the tagQueries page rather than on the map.
This is a trivial change to the server code to change the column that is queried, but needs a database import to add the 'industrial' column to the database - job for the weekend of 19 November.

**Comment by craigloftus** [comment]
As this sounds like a major job, can we review what other keys are being pulled? Some that might be missing include:

brand=*
tourism=\* 
operator=*
addr:_=_
opening_hours=*

**Comment by jones139** [comment]
Yup - need to get them all in one go!

from my phone

On 17 Nov 2011 12:03, "craigloftus" <
reply@reply.github.com>
wrote:

As this sounds like a major job, can we review what other keys are being
pulled? Some that might be missing include:

brand=*
tourism=*
operator=*
addr:_=_
opening_hours=*

---

**Comment by craigloftus** [comment]
Graham Jones wrote:

> Yup - need to get them all in one > go!

I think you can probably forget about the addr:\* keys as per my comments on
the enhancement issue.

Craig

**Comment by craigloftus** [comment]
Might you also include real_beer=*?

**Comment by jones139** [comment]
I think I have real_ale - do we need both?

from my phone

On 18 Nov 2011 12:31, "craigloftus" <
reply@reply.github.com>
wrote:

Might you also include real_beer=*?

---

**Comment by craigloftus** [comment]
No not really. Maybe if we expand beyond the Uk we can then consider a more
generic tag.
