### ISSUE TITLE
Add layer selector

### ISSUE THREAD

**Issue by jones139** [jones139/BrewMap#16]
Add a layer selector so you can switch off (say) microbreweries etc.   Probably means re-cycling right hand pane, so will make right hand pane a tab selectable pane for the key, statistics or layer switcher.

**Comment by craigloftus** [comment]
I've just committed initial work to support this (98f7a4ba37378c3f67644cb763f7d8724920c512).

It makes use of the built in leaflet support for grouping markers, with a simple event handler on each row in the key.

Hiding a layer is nice and quick, but leaflet is actually removing all the markers, and you have to add them all back again to re-display. I'm going to file an issue with leaflet to see if the behaviour can be improved.

**Comment by jones139** [comment]
Thanks - Looks good - I have deployed it on http://maps.webhop.net/BrewMap for now - will test it a bit and deploy it on the main site this evening.

I hadn't managed to work out how to hide a marker without removing it altogether either - it does seem like there is a 'visible' property missing from the Leaflet layer type.   I might have a look at the Leaflet code to see what I can do - I would like to add a 'collision detection' feature so that it will not draw all the overlapping icons - a bit like mapnik does.

**Comment by jones139** [comment]
Seems to work well to me, thanks.  Have deployed it on main brewmap map (http://brewmap.maps3.org.uk).  Will close this issue as you have it working, and we can open others if we come up with possible enhancements.

**Comment by craigloftus** [comment]
I've just commented on a Leaflet issue on the problem:
https://github.com/CloudMade/Leaflet/issues/4

On 25 November 2011 17:26, Graham Jones
reply@reply.github.com
wrote:
