### ISSUE TITLE
Improve Microbrewery Icon

### ISSUE THREAD

**Issue by rnorris** [jones139/BrewMap#17]
The microbrewery icon looks a little too much like wine for my tastes.

Perhaps a beer glass would be better e.g. (if Unixy and Navit installed)::
/usr/share/navit/icons/beer.png

Which I think is from:
http://www.openclipart.org/
(website not very functional at time of writing)

Addition:
Maybe this would be good for distilleries:
http://www.dementia5.com/community/Themes/default/images/drinks/Whiskey.png
Although I can't determine the license on those images

**Comment by jones139** [comment]
I'll have a look at those, thanks.  I have given my daughter the challenge of drawing the 1/2/3 barrel version that someone suggested on the mailing list too - if I get some icons collected together I can do a couple of versions to see what people prefer.

**Comment by rnorris** [comment]
How's this progressing?

It would be nice if the website had a beer glass for a favicon too.

[Would make it easier for me to find the site in my bookmarks list!]

**Comment by jones139** [comment]
Thanks for the reminder - to he hones, I had forgotten - sorry!
Will try to have a go at it over the next couple of evenings, but I am open
to pull requests if you want to fork the repository and make the changes
yourself?

Cheers

Graham.

On 14 January 2012 10:41, Rob Norris <
reply@reply.github.com

> wrote:
> 
> How's this progressing?
> 
> It would be nice if the website had a beer glass for a favicon too.
> 
> [Would make it easier for me to find the site in my bookmarks list!]
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jones139/BrewMap/issues/17#issuecomment-3491396

## 

Graham Jones
Hartlepool, UK.

**Comment by rnorris** [comment]
OK I'll setting it up
