### ISSUE TITLE
Web Page Layout Percentage Size

### ISSUE THREAD

**Issue by rnorris** [jones139/BrewMap#20]
I find the web page layout doesn't use much of my display window.

Wouldn't it be better to set the sizes of stuff in brewmap.css as percentages rather than in fixed pixels.

**Comment by jones139** [comment]
Good idea - I just steered away from that in case it became unusable on small screens, but you are right, most people will look at this on a desktop - I will give it a go and see how it works.

**Comment by jones139** [comment]
Fixed by craig's changes above.
