### ISSUE TITLE
Vineyards

### ISSUE THREAD

**Issue by craigloftus** [jones139/BrewMap#22]
I'm not sure landuse=vineyard is an appropriate tag to be tracking. It describes in general what a piece of land is being used for rather than indicating that a producer of wine is there. Additionally, the craft|industrial=winery tags is not being tracked.

An example is Stanlake Park near Twyford which is a winery [1] with attached vineyard [2]. Currently, just the vineyard is showing.

Another example of where this is a problem is the Denbies Wine Estate near Dorking which has 2 separate landuse areas ([3],[4]) both marked landuse=vineyard, which currently appear as two separate entities on the map. See issue #23 for my suggest of how to associate the 2.

[1] http://www.openstreetmap.org/browse/way/137952636
[2] http://www.openstreetmap.org/browse/way/137952641
[3] http://www.openstreetmap.org/browse/way/31864235
[4] http://www.openstreetmap.org/browse/way/31864240

**Comment by jones139** [comment]
Well, I have separated out wineries so they show up now - not sure why they were not - they should have been showing as vineyards.
As to whether to show vineyards or not, I don't know - I quite like vineyards, but you are right, it is the same as showing barley fields....
