### ISSUE TITLE
Adding support for relations

### ISSUE THREAD

**Issue by craigloftus** [jones139/BrewMap#23]
In issue #22 I mention the Denbies Wine Estate near Dorking which has 2 separate landuse areas ([1],[2]) both marked landuse=vineyard, which currently appear as two separate entities on the map. The way to resolve this is using relations to associate the ways. I couldn't think of anything more appropriate, so I used a site relation [3].

[1] http://www.openstreetmap.org/browse/way/31864235
[2] http://www.openstreetmap.org/browse/way/31864240
[3] http://www.openstreetmap.org/browse/relation/1858412

**Comment by jones139** [comment]
This is a difficult one - my database is produced using osm2pgsql, which
does not support site relations, which is why it is not showing up.
 Assuming we fix osm2pgsql to store the relation as a single geogaphic
feature, what would we want it to do - include the individual vineyards and
the geometry of the combination of the two, or not store the individual
ones?
If we store them all he server code would have to check if an area is part
of a relation before deciding whether to add it to the output....

Graham.

On 22 November 2011 18:14, craigloftus <
reply@reply.github.com

> wrote:
> 
> In issue #22 I mention the Denbies Wine Estate near Dorking which has 2
> separate landuse areas ([1],[2]) both marked landuse=vineyard, which
> currently appear as two separate entities on the map. The way to resolve
> this is using relations to associate the ways. I couldn't think of anything
> more appropriate, so I used a site relation [3].
> 
> [1] http://www.openstreetmap.org/browse/way/31864235
> [2] http://www.openstreetmap.org/browse/way/31864240
> [3] http://www.openstreetmap.org/browse/relation/1858412
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jones139/BrewMap/issues/23

## 

Graham Jones
Hartlepool, UK.

**Comment by craigloftus** [comment]
> This is a difficult one - my database is produced using osm2pgsql, which does not support site relations, which is why it > is not showing up.

Is this just site relations, or is it lacking support for relations entirely?

> what would we want it to do -  include the individual vineyards and the geometry of the combination of the
> two, or not store the individual ones?

From issue #22 you can guess that I'm in favour of dropping vineyards entirely. Not because I have some particular dislike for them, but because the current way of tagging them is rubbish and they seem to be outside the original scope of the project. If we were to include them (even with improved tagging) we should also consider hop fields/yards and their associated oast houses etc.?

In terms of handling the relation, I think just taking the tags from the relation would be most appropriate and forget the members and put the label on the centroid of the combined relation area. I have no idea how difficult any of this is...? If it is all very difficult then I would to just tag Denbies in a simpler way, such as a node.

I don't want to keep suggesting lists... but, perhaps we could provide a list of vineyards and suggest they be checked to see if they should be 'upgraded' to wineries?

**Comment by jones139** [comment]
A 'possible winery' list sounds good - then I can recycle the grapes icon as a winery.   I'll just add them to tagQueries for now.

**Comment by jones139** [comment]
Forgot to add, osm2pgsql has limited support for relations:
"6) The relations are parsed. Osm2pgsql has special handling for a
 limited number of types: multipolygon, route, boundary
 The code will build the appropriate geometries by referencing the
 members and outputing these into the database."

(from https://github.com/openstreetmap/osm2pgsql).

I would suggest we close this issue now we have moved vineyards to the tagQueries list?

**Comment by craigloftus** [comment]
Agreed.
