### ISSUE TITLE
Is the edit button necessary?

### ISSUE THREAD

**Issue by craigloftus** [jones139/BrewMap#7]
The link to browse the data in the pop-up provides basically the same functionality doesn't it?

**Comment by jones139** [comment]
The edit button on the main page is there in case you want to add a brewery that is not on the map - to save going to find the area you were interested in on the main OSM page.   I think the edit links on the tagQueries page are superfluous though so these could go?

**Comment by craigloftus** [comment]
Ah I see. I misunderstood its purpose.
