### ISSUE TITLE
JSON data contains keys with null values

### ISSUE THREAD

**Issue by craigloftus** [jones139/BrewMap#9]
Properties that are not defined for a given entity in the data set are being encoded into the JSON files as property=null. It would be better to just drop these, we have to test for existence in the JS client anyway.

**Comment by jones139** [comment]
You mean just do not define 'craft' if craft is null, and let the JS side check for existence?   It will just mean that the JS code will have to check for every entity before it uses it?

**Comment by craigloftus** [comment]
Graham Jones wrote:

> You mean just do not define 'craft' if craft is null, and let the JS side
> check for existence?   It will just mean that the JS code will have to
> check for every entity before it uses it?

Yep that is what I mean. The JS code has to check for null anyway and there
is no difference with checking for undefined. So unless it is an issue for
the server side code we may as well reduce the data sent.

**Comment by jones139** [comment]
Done - have deployed the change to the server code, and your javascript client code to the main server at brewmap.maps3.org.uk....seems to work.
